### ISSUE TITLE
No pen input available RM 2

### ISSUE THREAD

**Issue by Brandieee** [dixonary/draft-reMarkable#28]
On the reMarkable 2
Using rm2fb per https://github.com/ddvk/remarkable2-framebuffer/issues/35

Touchinput and starting apps etc works great, however the pen doesn't seem to be recognized at all as an input device.

**Comment by Eeems** [comment]
Pen input doesn't work on the rM1 either, it's due to how the Qt framework handles pen and touch differently. I work around this (somewhat) in oxide by creating fake mouse events for pen input: https://github.com/Eeems/oxide/blob/master/applications/launcher/eventfilter.cpp#L106-L143
This is an imperfect solution though as my implementation of wigetsAt has a couple bugs, and it doesn't properly detect when a widget is obscured by another and thus shouldn't get the mouse event.

**Comment by dixonary** [comment]
Yes, this is accurate. I'm afraid it's difficult to support in a convenient way.

**Comment by dixonary** [comment]
I'll close this for now, given the low interaction nature of draft anyway.
